# Site settings
title: make mobile
email: imagine@makemobile.io
url: http://makemobile.io
description: "make mobile company website - iPhone and iPad software consulting"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: make mobile

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/rich2255
  - title: linkedin
    url: https://www.linkedin.com/in/richardaball/en

# Build settings
markdown: kramdown
permalink: pretty
